pos_tweets = [('@J_McCooeye @alllibertynews @ElsarioD @JulieBorowski @obama_speech libs with Hil liar Clinton and Benghazi. Good luck with that. Trump!!', 'positive'),
('Their dire warnings and feigned concern about a Trump nom are BS. Their actions tell us everything we need to know', 'positive'),
('Well Trump may have lost to Kasich in Ohio but in my home county Trump prevailed', 'positive'),
('@davidaxelrod is cnn dragging tonight out, NBC and other outlets called it for Clinton and Trump over 30 minutes ago and say 100% vote in', 'positive'),
('Just to let you guys know when it was 99% in Missouri I CALLED IT A WIN FOR DONALD  If he wins see ya all could have listen to me N went bed', 'positive'),
('If I have to choose to vote for Republican Hillary or Republican Trump for President, then I will vote for the one running as a Republican!', 'positive'),
('@davidaxelrod is cnn dragging tonight out, NBC and other outlets called it for Clinton and Trump over 30 minutes ago and say 100% vote in', 'positive'),
('@TrumpTrain8 lives will be lost if they fuck trump.', 'positive'),
('@risetoflyy gov of MO called it for TRUMP', 'positive'),
('@risetoflyy gov of MO called it for TRUMP', 'positive'),
('Pissed Trump didnt win Ohio. But ya cant have it all I guess', 'positive'),
('Im really hoping #Kasich wins. Trump is a nightmare..literally.', 'positive'),
('Fidel Castro is a Communist just like you not like Trump! @VanJones68', 'positive'),
('@ChristieFridman @lisamarie418 #PRESIDENT TRUMP WH DC 2016!', 'positive'),
('Pissed Trump didnt win Ohio. But ya cant have it all I guess', 'positive'),
('My delegates count are by Fox CNN I notice always back track Trump 621 on Fox CNN has him at 640', 'positive'),
('@TheFive Not voting Trump b/c of SCOTUS appts is irrelevant @kimguilfoyle . Trump already "burned down the GOP". Why not burn it all down?', 'positive'),
('@ItsRickBitches Fox has him 621', 'positive'),
('@seanhannity @dariana_ortiz No she cant i dont where people keep saying that Hillary will beat Trump in this election.', 'positive'),
('#SayNoToSocialism #AnyoneButBernie #NotFeelingTheBern #Trump2016 https://t.co/2VWGgm5pvI', 'positive'),
('Just wanna let you guys know Trump lost to Kasich in Ohio BUT DONALD J MOTHER FUCKING TRUMP HAD MORE VOTE THAN @HillaryClinton  FUCKING AAAA', 'positive'),
('@JoelWeidenhamer ohio, your display of affection for kasich didnt stop Trump in the end. Hes on fire and hell be back for the general.', 'positive'),
('@FoxNews Ill take Trump, even if he is cheated out of it by Kasichs brokered convention, Ill write him in.', 'positive'),
('#AlwaysTrump #Trump2016 #PresidentTrump  #TrumpTrain #OnlyTrump  https://t.co/ER1KbyiD55', 'positive'),
('Never be tricked by Rep again.#only Independent #OnlyTrump #Not much dif between Rep&amp; Dems anyway https://t.co/m7npWuE36s', 'positive'),
('Trump 99 Delegates Florida .. Illinois 24 Awarded soooo far everybody else 0 .. NorthCarolina Trump 29 Cruz 26...Missouri tied 11 TRUMP CRUZ', 'positive'),
('.@Maggie1715 @TheRightScoop Theyd better call it for Trump and move on but GOPe will probably want to give it to Cruz, so expect a recount.', 'positive'),
('Pissed Trump didnt win Ohio. But ya cant have it all I guess', 'positive'),
('@RichardGrenell @KatiePavlich EXCLUSIVE: Newt Gingrich: If Trump Wins Big in Florida, They Wont Be Able to Stop Him https://t.co/NblOLOhvrG', 'positive'),
('@lucaslumm war is not inevitable why do you think trump wants to remain neutral with the middle east', 'positive'),
('@TrumpTrain8 lives will be lost if they fuck trump.', 'positive'),
('@lucaslumm war is not inevitable why do you think trump wants to remain neutral with the middle east', 'positive'),
('@PaulBegala @davidgregory GOP or not as long as Trump is president who cares about the GOP.', 'positive'),
('@Swiger13 sorry John but my home county a predominantly dem one with a GOP party that kisses Kasich ass went 4 Trump.', 'positive'),
('.@joyreaper They ALWAYS hold back Trump wins as long as possible!!!', 'positive'),
('#anybodybuthillary  VOTE GOP! All 3 would be great. Trump talks tough. Good..America needs balls. Obama failed USA. Yay. Good riddance', 'positive'),
('Missouri for Trump https://t.co/eAd5vuFLvD', 'positive'),
('@USAHipster @Amberis4LSU @AC360 #PRESIDENT TRUMP WH DC 2016!', 'positive'),
('@FoxNews @foxandfriends @JohnKasich to stay in race just as a spoiler to negate the peoples votes for Trump is disgraceful! !!', 'positive'),
('@Swiger13 sorry John but my home county a predominantly dem one with a GOP party that kisses Kasich ass went 4 Trump.', 'positive'),
('@politico come on Cruz. We dont need an actor for president', 'positive'),
('@risetoflyy @tedcruz "we are the only ones who beat trump"', 'positive'),
('@nicktjacob @ellencarmichael I support Cruz and Im sorry Rubio lost Florida. Hes a good man who fought the good fight.', 'positive'),
('@washingtonpost @tedcruz What can be done about this?', 'positive'),
('#PAprimary #CAprimary #AZprimary #WIprimary #NEprimary #UniteWithCruz to #StopTrump #ChooseCruz #NeverTrump  https://t.co/heqBUADtWs', 'positive'),
('We" hope "Donald Trump keeps his promises. WE KNOW Ted Cruz  Will keep his !', 'positive'),
('Actions speak louder than words. If Rubio &amp; Kasich were truly worried about conserv mvt, wouldve bowed out a week ago &amp; teamed up w/ Cruz', 'positive'),
('Only reason @BernieSanders lost today was because of a low voter turn out--spring break #FeelTheBern #SuperTuesday', 'positive'),
('#ThingsITrustMoreThanHillaryClinton #NeverHillary #HillaryForPrison2016 #HillNo #OnlyBernie #ImWithHim #BernieorBust https://t.co/X0Wvyz5rXf', 'positive'),
('Nonsense. Your *lie* was claiming Hillary had a 3x lead over Bernie in the pledged delegates. Its 1155-855. #DNC', 'positive'),
('Lets get these states VOTING #BernieSanders  its critical to get the young old &amp; undecided to the polls https://t.co/zBzxnqLn55', 'positive'),
('Only reason @BernieSanders lost today was because of a low voter turn out--spring break #FeelTheBern #SuperTuesday', 'positive'),
('How many people are for a @HillaryClinton and @BernieSanders ticket? . #SuperTuesday3 #Elections2016 #ReadyForHillary #FeelTheBern', 'positive')]

neg_tweets = [('@AnonHerb3 @rosevine3 @37thRealm Wonderful way to give the election to Trump.', 'negative'),
('Is it really about to be Hillary vs Trump for president? How can a country like the U.S. really not get better candidates than this?', 'negative'),
('@TrumpTrain8 @Ricky_Vaughn99   THE AGONY OF DEFEAT!!!  They not in healthy state of mind. Ted needs to PRAY for them!!', 'negative'),
('Is it really about to be Hillary vs Trump for president? How can a country like the U.S. really not get better candidates than this?', 'negative'),
('I mean, this lady even looks like shes a Trump supporter. And shes covered in white paint and Im confused. #previoustweet', 'negative'),
('Praying any Republican candidate (I guess Cruz at this point) beats Trump like the panic attacks are becoming so real', 'negative'),
('Im afraid he wont beat her in the general election.  https://t.co/2fA4YBBFjW', 'negative'),
('Can somebody give me a logical reason to vote for Trump? ', 'negative'),
('@LovinJK4Ever @DonnieWahlberg  the bees need sting Trumps ass', 'negative'),
('#PAprimary #CAprimary #AZprimary #WIprimary #NEprimary #UniteWithCruz to #StopTrump #ChooseCruz #NeverTrump  https://t.co/heqBUADtWs', 'negative'),
('@JonahNRO Haha, the Trump troll farms are becoming more civil. Trying to woo us away fr our principles. Only works on the feeble minded tho.', 'negative'),
('Millions of #Repubs have crossed aisle to vote for Hillary. They believe that Trump can beat her. Its the ONLY reason, shes in the lead.', 'negative'),
('A lady just walked into this Dennys with a Trump button and now I want to leave immediately. ', 'negative'),
('@iAmGeorgi   We Dems must Unite and Fight to #StopTrump ', 'negative'),
('@dickfundy I disagree, but I know what we can all agree on. Trump sucks.', 'negative'),
('Trump is all sorts of terrible things but hes not stupid. Playing peoples fears to get into power.#HillaryforPresident', 'negative'),
('Trump is all sorts of terrible things but hes not stupid. Playing peoples fears to get into power.', 'negative'),
('@CRKittle Hmmmm EVERY poll shows now Trump loses to Hillary and wth do we need yall for in Nov?', 'negative'),
('I voted ! But not for that bitch ass Trump.', 'negative'),
('Trump is all sorts of terrible things but hes not stupid. Playing peoples fears to get into power.', 'negative'),
('@davidplouffe You are so talented. Jump over the Republican side and help us get Cruz or anyone but Trump elected. #NeverTrump', 'negative'),
('S/o to the Trump campaign for the racist uneducated &amp; politically uninformed cockroaches scattered on my newsfeed GROSS #DumpTrump', 'negative'),
('Unofficially... Winner: Clinton wins all 5 states tonight. Winner: Trump wins 4/5 states tonight.', 'negative'),
('Loser: America.', 'negative'),
('@TimBartender Im straight up depressed. Im about to take a shot of Henney.. We need this to turn around or else its gonna be Pres. Trump', 'negative'),
('I have always respected others political opinions (even if I dont agree with them), but Trump as president is simply something I never can', 'negative'),
('@BroJoeyD I imagine he will, an independent run guarantees a President Cruz or Trump and he knows that.', 'negative'),
('@TheValuesVoter TRUMP gave a good speech griend cnn said Cruz have a victory speech and he didnt win anything', 'negative'),
('@TheValuesVoter TRUMP gave a good speech griend cnn said Cruz have a victory speech and he didnt win anything', 'negative'),
('@vivelafra Them 11 I did not add in has now been switched to 20 for Trump and 5 for Lying ass @tedcruz', 'negative'),
('@BlueWaterDays @tedcruz you dont stand a chance. Step down now. Or forever be a joke.', 'negative'),
('@vivelafra Them 11 I did not add in has now been switched to 20 for Trump and 5 for Lying ass @tedcruz', 'negative'),
('@GregFlippen I was quite impressed by Rubios exit speech but not so much with speeches by Kasich and Cruz ... you?', 'negative'),
('@BlueWaterDays @tedcruz you dont stand a chance. Step down now. Or forever be a joke.', 'negative'),
('@vivelafra Them 11 I did not add in has now been switched to 20 for Trump and 5 for Lying ass @tedcruz', 'negative'),
('Cruz third in Ohio and Florida. He couldnt beat Kasich or Rubio.', 'negative'),
('@auntsnitzi @Wicked3s @tedcruz I thought he was giving a Loooonnnngggg Boring SERMON, and he didnt even win 1 State!  SMH...', 'negative'),
('@hippygirl37 Cnn just awarded 11 Delegates to Trump and 11 Delegates to Lying ass Cruz', 'negative'),
('Cruz currently rigging Missouri prepare for him to magically get 2000 votes', 'negative'),
('@vivelafra Them 11 I did not add in has now been switched to 20 for Trump and 5 for Lying ass @tedcruz', 'negative'),
('@jmattbarber LMFAO Dude is just like Cruz ....EVERY NIGHT CRUZ SAYS HE WINS', 'negative'),
('I believe what is taking Mo so long to finish count,is they trying to fix it for a Cruz win..no other reason! You watch, Im going to bed', 'negative'),
('Horrible night to Cruz.', 'negative'),
('@Gypsydragup @AnnCoulter @mboyle1 @tedcruz @realDonaldTrump Trump could end up wth more votes 2. That wud b shameful 4 Ted!! Jus sayin!!', 'negative'),
('@DanScavino and to get Cruz off the T.V ...PLEASE  !!!', 'negative'),
('Can we all just stop talking about hitler trump, baby kacish, old man bern, criminal Hillary, And big nose Cruz, and focus on march madness?', 'negative'),
('@jmattbarber LMFAO Dude is just like Cruz ....EVERY NIGHT CRUZ SAYS HE WINS', 'negative'),
('Regardless of who the democratic nominee is, remember.. Anybody but trump/Cruz. Clinton will have my vote if she wins the dem nomination.', 'negative'),
('Trump or Cruz lol... For the rational partiers - read Dems - this is more priceless than McCain picking Palin ', 'negative'),
('Cruz third in Ohio and Florida. He couldnt beat Kasich or Rubio.', 'negative'),
('Trump or Cruz lol... For the rational partiers - read Dems - this is more priceless than McCain picking Palin ', 'negative'),
('Thats right @TedCruz ...they want @realDonaldTrump not you! You sound like all the rest. https://t.co/kSKQyISjNH', 'negative'),
('CNN now has Donald with 20 Delegates for Missouri and five for LYING ASS @tedcruz ..... Weeeeeeeeeeeeeeeeeeee', 'negative'),
('@BlueWaterDays @tedcruz you dont stand a chance. Step down now. Or forever be a joke.', 'negative'),
('@realDonaldTrump News media do your job and report that this was a definitive WIN  for Donald Trump. Cruz is done!', 'negative'),
('Horrible night to Cruz.', 'negative'),
('@realDonaldTrump News media do your job and report that this was a definitive WIN  for Donald Trump. Cruz is done!', 'negative'),
('@ItsRickBitches Cruz took a pounding tonight........... PORN STYLE ..... HE WAS DEEP THROATED', 'negative'),
('wut https://t.co/2YEkpokdS4', 'negative'),
('@hippygirl37 Cnn just awarded 11 Delegates to Trump and 11 Delegates to Lying ass Cruz for Missouri.... Trump still leading in Missouri', 'negative'),
('Wonder where all the Bernie supporters were today', 'negative'),
('Jill Stein is honestly fifty times way cooler than Bernie and few know who she is considering she is still green and not blue', 'negative'),
('#SayNoToSocialism #AnyoneButBernie #NotFeelingTheBern #Trump2016 https://t.co/2VWGgm5pvI', 'negative'),
('@PatKirwanCBS @dinocleveland @Browns @NDSUfootball Im not sure about Wentz or Bernie Sanders...?', 'negative'),
('I dont care for Sanders much but what was Couric even trying to get at here?... I dont understand lol  https://t.co/xtTozD93VC', 'negative'),
('@runonlove not you using CARLY FIORINA of all people Bc ur a mad Bernie bro', 'negative'),
('I dont care for Sanders much but what was Couric even trying to get at here?... I dont understand lol  https://t.co/xtTozD93VC', 'negative'),
('Bernie ppl need to have a public discussion of the new 110% effort it will take. What is the code for beating the Hillary boss in level 9.', 'negative'),
('@BernieSanders you just sound like a dumb fuck. Normally dont tweet at people but damn, what a dumb old man! I could go on but I wont.', 'negative'),
('Wonder where all the Bernie supporters were today ', 'negative'),
('Unless your names Bernie. Then, youll lie abt opponents record &amp; your husband will call his voters, teabaggers. https://t.co/H42FpyiRHJ', 'negative'),
('@denman_nick you love Bernie cuz u want free shit', 'negative'),
('Bernies done  https://t.co/9DyR3GYyrn', 'negative'),
('A lot of tv people said he wasnt gracious to Sen Rubio, well here is the clip!! #NeverHillary #gop  https://t.co/7XN9rLM8RK', 'negative'),
('ONLY Clinton stans do #Storify. Why? No one else has the perpetual need to play victim, 24/7. Tata, Davey Boy! #DNC https://t.co/ewmBW0tWSd', 'negative'),
('Just wanna let you guys know Trump lost to Kasich in Ohio BUT DONALD J MOTHER FUCKING TRUMP HAD MORE VOTE THAN @HillaryClinton  FUCKING AAAA', 'negative'),
('Nonsense. Your *lie* was claiming Hillary had a 3x lead over Bernie in the pledged delegates. Its 1155-855. #DNC https://t.co/vdR7lix5AN', 'negative'),
('Can we all just stop talking about hitler trump, baby kacish, old man bern, criminal Hillary, And big nose Cruz, and focus on march madness?', 'negative'),
('Can we all just stop talking about hitler trump, baby kacish, old man bern, criminal Hillary, And big nose Cruz, and focus on march madness?', 'negative'),
('@HillaryClinton the white padded cell maybe #FeelTheBern #HillaryForPrison2016 #Trump2016 #CruzCrew #CruzControl #MakeAmericaGreatAgain', 'negative'),
('@dcexaminer When you write a story on the OBAMA/CLINTON POLITBUROs, well read this article. MSM write bad story on Hillary~NO ACCESS to her', 'negative'),
('@USATODAY @FiercelyZen Minus the gullible Black vote #Hillary2016 isnt winning large enough majority of Anglo DEMS to win general election', 'negative'),
('@JonahNRO @drwhew @seanhannity TRUMP beats Hillary', 'negative')]


test_pos = [('Thank you @BernieSanders for sticking it out until the #convention. Its really important to all of us supporters that your ideals live on.', 'positive'),
('well...get ready for President Trump. I WILL FUCKING NEVER VOTE FOR #HILLARY2016 NO REAL BERNIE SUPPORTER WILL EVER VOTE FOR THAT BITCH!', 'positive'),
('Thank you @BernieSanders for sticking it out until the #convention. Its really important to all of us supporters that your ideals live on.', 'positive'),
('Right On!! Work together @BernieSanders as the candidate!@SenWarren https://t.co/bVjYNld2Ip', 'positive'),
('Nonsense. Your *lie* was claiming Hillary had a 3x lead over Bernie in the pledged delegates. Its 1155-855. #DNC https://t.co/vdR7lix5AN', 'positive'),
('Bernie and I have similar feelings on not being able to fall asleep before 2 a.m. every day https://t.co/Lmp6kqd9cY', 'positive'),
('Great platform speech by #BernieSanders https://t.co/v8HjaGgGmz @jjhorgan shld take some lessons in style and substance #bcpoli', 'positive'),
('Lets get these states VOTING #BernieSanders  its critical to get the young old &amp; undecided to the polls https://t.co/zBzxnqLn55', 'positive'),
('@JesseLehrich  A near clean sweep! #HillaryStrong Thank you Ohio!', 'positive'),
('@iAmGeorgi We Dems must Unite and Fight to #StopTrump #HillaryforPresident', 'positive'),
('.@HillaryClinton five-state sweep means its time for a celebration!  #YaasHillary https://t.co/N6sqDscJBw', 'positive'),
('How many people are for a @HillaryClinton and @BernieSanders ticket?  . #SuperTuesday3 #Elections2016 #ReadyForHillary #FeelTheBern', 'positive'),
('Im just going to drop this in. #HillaryBlowout #Believe https://t.co/NYw84IpCFb', 'positive'),
('Big winners tonight: Hillary Clinton, Black Lives Matter, DJ Trump, my election predictions...', 'positive'),
('Wasnt for TRUMP hardly anyone would even watch..Hillary was ficed party new Hillary win over 74socolist #CNNElection', 'positive'),
('Wow. No one expected her to go 5/5 tonight  https://t.co/GKZ6NlE07n', 'positive'),
('So, to summarize our choices: We have (A) Hillary Clinton, or (B) Someone who really admires Hillary Clinton. #Merica2016', 'positive'),
('So, if you appropriately call Hillary a bitch, youre a misogynist? Ok. Then, shes a scumbag &amp; dickhead. Why? Shes a Repub. #PrimaryDay', 'positive'),
('How many people are for a @HillaryClinton and @BernieSanders ticket? . #SuperTuesday3 #Elections2016 #ReadyForHillary #FeelTheBern', 'positive'),
('FL, NC, OH, IL, MO 5/5 Tonight. #HillYes #ImWithHer]', 'positive'),
('Not sure how i will pick the finals!?! Trumps KKK lynching or Hillarys profit prison for life!', 'negative')]


test_neg = [('Bernie ppl need to have a public discussion of the new 110% effort it will take. What is the code for beating the Hillary boss in level 9.', 'negative'),
('Is @DanaBashCNN supposed to be a paid hack for Hillary, like you? SMDH! #DNC https://t.co/Dheo602ElK', 'negative'),
('Can we all just stop talking about hitler trump, baby kacish, old man bern, criminal Hillary, And big nose Cruz, and focus on march madness?', 'negative'),
('Just in: Hillary declares herself President! No further need to vote, she says. https://t.co/k6Pz1zYFER', 'negative'),
('@SouthLoneStar @ironetc2 no way .Hillary is the phony she talks black in the south shes talking down to them...anything to get a vote', 'negative'),
('Nonsense. Your *lie* was claiming Hillary had a 3x lead over Bernie in the pledged delegates. Its 1155-855. #DNC https://t.co/vdR7lix5AN', 'negative'),
('So, if you appropriately call Hillary a bitch, youre a misogynist? Ok. Then, shes a scumbag &amp; dickhead. Why? Shes a Repub. #PrimaryDay', 'negative'),
('Can we all just stop talking about hitler trump, baby kacish, old man bern, criminal Hillary, And big nose Cruz, and focus on march madness?', 'negative'),
('These people want us to believe that a guy who only won a single county in his home state was the best candidate to beat Hillary? Please.', 'negative'),
('Can we all just stop talking about hitler trump, baby kacish, old man bern, criminal Hillary, And big nose Cruz, and focus on march madness?', 'negative')]

